name: Build Sphinx and Push Pages
# on: [push, pull_request, workflow_dispatch]
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'github-pages'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          cd docs && sphinx-build source build/html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
